name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build x86
        run: msbuild /p:Configuration=Release;Platform=x86
      - name: Build x64
        run: msbuild /p:Configuration=Release;Platform=x64
      - name: Create x86 artifact
        run: 7z a x86.zip bin/Release/x86
      - name: Upload x86
        uses: actions/upload-artifact@v1
        with:
          name: x86
          path: x86.zip
      - name: Create x64 artifact
        run: 7z a x64.zip bin/Release/x64
      - name: Upload x64
        uses: actions/upload-artifact@v1
        with:
          name: x64
          path: x64.zip
