name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build x86
        run: msbuild /p:Configuration=Release;Platform=x86
      - name: Build x64
        run: msbuild /p:Configuration=Release;Platform=x64
      - name: Upload x86
        uses: actions/upload-artifact@v1
        with:
          name: x86
          path: bin/x86/Release
      - name: Upload x64
        uses: actions/upload-artifact@v1
        with:
          name: x64
          path: bin/x64/Release
